apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-server-svc
  name: blog-server-svc
spec:
  ports:
    - port: 50005
      protocol: TCP
      targetPort: 50005
  selector:
    app: blog-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-server-deployment
  labels:
    app: blog-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-server
          image: server-ko
          ports:
            - containerPort: 50005
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-svc.default.svc.cluster.local:27017"
            - name: SERVER_PORT
              value: "50005"